syntax = "proto3";

package course;

option go_package = "course-service/proto/coursepb";

message CreateCourseRequest {
  string title       = 1;
  string description = 2;
  double price       = 3;
}

message GetCourseRequest {
  string course_id = 1;
}

message UpdateCourseRequest {
  string course_id   = 1;
  string title       = 2;
  string description = 3;
}

message DeleteCourseRequest {
  string course_id = 1;
}

message CourseResponse {
  string id          = 1;
  string title       = 2;
  string description = 3;
  string tutor_id    = 4;
  double price       = 5;
}

message CoursesList {
  repeated CourseResponse courses = 1;
}

message Empty {}

service CourseService {
  rpc CreateCourse(CreateCourseRequest)  returns (CourseResponse);
  rpc GetCourse(GetCourseRequest)        returns (CourseResponse);
  rpc GetAllCourses(Empty)               returns (CoursesList);
  rpc UpdateCourse(UpdateCourseRequest)  returns (CourseResponse);
  rpc DeleteCourse(DeleteCourseRequest)  returns (Empty);
}
