// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.30.2
// source: proto/lesson.proto

package lessonpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LessonServiceClient is the client API for LessonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LessonServiceClient interface {
	CreateLesson(ctx context.Context, in *CreateLessonRequest, opts ...grpc.CallOption) (*Lesson, error)
	GetLesson(ctx context.Context, in *GetLessonRequest, opts ...grpc.CallOption) (*Lesson, error)
	GetCourseLessons(ctx context.Context, in *GetCourseLessonsRequest, opts ...grpc.CallOption) (*CourseLessonsList, error)
	UpdateLessonStatus(ctx context.Context, in *UpdateLessonStatusRequest, opts ...grpc.CallOption) (*Lesson, error)
	DeleteLesson(ctx context.Context, in *DeleteLessonRequest, opts ...grpc.CallOption) (*Empty, error)
	GetMySchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*CourseLessonsList, error)
	AddMaterial(ctx context.Context, in *AddMaterialRequest, opts ...grpc.CallOption) (*MaterialResponse, error)
	GetLessonMaterials(ctx context.Context, in *GetLessonMaterialsRequest, opts ...grpc.CallOption) (*MaterialsList, error)
	GetAttendance(ctx context.Context, in *GetAttendanceRequest, opts ...grpc.CallOption) (*AttendanceList, error)
}

type lessonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLessonServiceClient(cc grpc.ClientConnInterface) LessonServiceClient {
	return &lessonServiceClient{cc}
}

func (c *lessonServiceClient) CreateLesson(ctx context.Context, in *CreateLessonRequest, opts ...grpc.CallOption) (*Lesson, error) {
	out := new(Lesson)
	err := c.cc.Invoke(ctx, "/lesson.LessonService/CreateLesson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonServiceClient) GetLesson(ctx context.Context, in *GetLessonRequest, opts ...grpc.CallOption) (*Lesson, error) {
	out := new(Lesson)
	err := c.cc.Invoke(ctx, "/lesson.LessonService/GetLesson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonServiceClient) GetCourseLessons(ctx context.Context, in *GetCourseLessonsRequest, opts ...grpc.CallOption) (*CourseLessonsList, error) {
	out := new(CourseLessonsList)
	err := c.cc.Invoke(ctx, "/lesson.LessonService/GetCourseLessons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonServiceClient) UpdateLessonStatus(ctx context.Context, in *UpdateLessonStatusRequest, opts ...grpc.CallOption) (*Lesson, error) {
	out := new(Lesson)
	err := c.cc.Invoke(ctx, "/lesson.LessonService/UpdateLessonStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonServiceClient) DeleteLesson(ctx context.Context, in *DeleteLessonRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/lesson.LessonService/DeleteLesson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LessonServiceServer is the server API for LessonService service.
// All implementations must embed UnimplementedLessonServiceServer
// for forward compatibility
type LessonServiceServer interface {
	CreateLesson(context.Context, *CreateLessonRequest) (*Lesson, error)
	GetLesson(context.Context, *GetLessonRequest) (*Lesson, error)
	GetCourseLessons(context.Context, *GetCourseLessonsRequest) (*CourseLessonsList, error)
	UpdateLessonStatus(context.Context, *UpdateLessonStatusRequest) (*Lesson, error)
	DeleteLesson(context.Context, *DeleteLessonRequest) (*Empty, error)
	MarkAttendance(context.Context, *MarkAttendanceRequest) (*Empty, error)
	GetMySchedule(context.Context, *GetScheduleRequest) (*CourseLessonsList, error)
	AddMaterial(context.Context, *AddMaterialRequest) (*MaterialResponse, error)
	GetLessonMaterials(context.Context, *GetLessonMaterialsRequest) (*MaterialsList, error)
	GetAttendance(context.Context, *GetAttendanceRequest) (*AttendanceList, error)
	mustEmbedUnimplementedLessonServiceServer()
}

// UnimplementedLessonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLessonServiceServer struct {
}

func (UnimplementedLessonServiceServer) CreateLesson(context.Context, *CreateLessonRequest) (*Lesson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLesson not implemented")
}
func (UnimplementedLessonServiceServer) GetLesson(context.Context, *GetLessonRequest) (*Lesson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLesson not implemented")
}
func (UnimplementedLessonServiceServer) GetCourseLessons(context.Context, *GetCourseLessonsRequest) (*CourseLessonsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseLessons not implemented")
}
func (UnimplementedLessonServiceServer) UpdateLessonStatus(context.Context, *UpdateLessonStatusRequest) (*Lesson, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLessonStatus not implemented")
}
func (UnimplementedLessonServiceServer) DeleteLesson(context.Context, *DeleteLessonRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLesson not implemented")
}
func (UnimplementedLessonServiceServer) GetMySchedule(context.Context, *GetScheduleRequest) (*CourseLessonsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMySchedule not implemented")
}
func (UnimplementedLessonServiceServer) mustEmbedUnimplementedLessonServiceServer() {}

// UnsafeLessonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LessonServiceServer will
// result in compilation errors.
type UnsafeLessonServiceServer interface {
	mustEmbedUnimplementedLessonServiceServer()
}

func RegisterLessonServiceServer(s grpc.ServiceRegistrar, srv LessonServiceServer) {
	s.RegisterService(&LessonService_ServiceDesc, srv)
}

func _LessonService_CreateLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonServiceServer).CreateLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lesson.LessonService/CreateLesson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonServiceServer).CreateLesson(ctx, req.(*CreateLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonService_GetLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonServiceServer).GetLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lesson.LessonService/GetLesson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonServiceServer).GetLesson(ctx, req.(*GetLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonService_GetCourseLessons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseLessonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonServiceServer).GetCourseLessons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lesson.LessonService/GetCourseLessons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonServiceServer).GetCourseLessons(ctx, req.(*GetCourseLessonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonService_UpdateLessonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLessonStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonServiceServer).UpdateLessonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lesson.LessonService/UpdateLessonStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonServiceServer).UpdateLessonStatus(ctx, req.(*UpdateLessonStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonService_DeleteLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonServiceServer).DeleteLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lesson.LessonService/DeleteLesson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonServiceServer).DeleteLesson(ctx, req.(*DeleteLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LessonService_ServiceDesc is the grpc.ServiceDesc for LessonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LessonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lesson.LessonService",
	HandlerType: (*LessonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLesson",
			Handler:    _LessonService_CreateLesson_Handler,
		},
		{
			MethodName: "GetLesson",
			Handler:    _LessonService_GetLesson_Handler,
		},
		{
			MethodName: "GetCourseLessons",
			Handler:    _LessonService_GetCourseLessons_Handler,
		},
		{
			MethodName: "UpdateLessonStatus",
			Handler:    _LessonService_UpdateLessonStatus_Handler,
		},
		{
			MethodName: "DeleteLesson",
			Handler:    _LessonService_DeleteLesson_Handler,
		},
		{
			MethodName: "MarkAttendance",
			Handler:    _LessonService_MarkAttendance_Handler,
		},
		{
			MethodName: "GetMySchedule",
			Handler:    _LessonService_GetMySchedule_Handler,
		},
		{
			MethodName: "AddMaterial",
			Handler:    _LessonService_AddMaterial_Handler,
		},
		{
			MethodName: "GetLessonMaterials",
			Handler:    _LessonService_GetLessonMaterials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lesson.proto",
}

// ── MarkAttendance extension ──────────────────────────────────────────────────

// Added without protoc regeneration — wire encoding requires protoc re-run.

func (UnimplementedLessonServiceServer) MarkAttendance(context.Context, *MarkAttendanceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkAttendance not implemented")
}

func _LessonService_MarkAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAttendanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonServiceServer).MarkAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/lesson.LessonService/MarkAttendance"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonServiceServer).MarkAttendance(ctx, req.(*MarkAttendanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LessonService_GetMySchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LessonServiceServer).GetMySchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/lesson.LessonService/GetMySchedule"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LessonServiceServer).GetMySchedule(ctx, req.(*GetScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func (c *lessonServiceClient) GetMySchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (*CourseLessonsList, error) {
	out := new(CourseLessonsList)
	err := c.cc.Invoke(ctx, "/lesson.LessonService/GetMySchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lessonServiceClient) AddMaterial(ctx context.Context, in *AddMaterialRequest, opts ...grpc.CallOption) (*MaterialResponse, error) {
	out := new(MaterialResponse)
	err := c.cc.Invoke(ctx, "/lesson.LessonService/AddMaterial", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (c *lessonServiceClient) GetLessonMaterials(ctx context.Context, in *GetLessonMaterialsRequest, opts ...grpc.CallOption) (*MaterialsList, error) {
	out := new(MaterialsList)
	err := c.cc.Invoke(ctx, "/lesson.LessonService/GetLessonMaterials", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}

func (UnimplementedLessonServiceServer) AddMaterial(context.Context, *AddMaterialRequest) (*MaterialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMaterial not implemented")
}
func (UnimplementedLessonServiceServer) GetLessonMaterials(context.Context, *GetLessonMaterialsRequest) (*MaterialsList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLessonMaterials not implemented")
}

func _LessonService_AddMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMaterialRequest)
	if err := dec(in); err != nil { return nil, err }
	if interceptor == nil { return srv.(LessonServiceServer).AddMaterial(ctx, in) }
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/lesson.LessonService/AddMaterial"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) { return srv.(LessonServiceServer).AddMaterial(ctx, req.(*AddMaterialRequest)) }
	return interceptor(ctx, in, info, handler)
}

func _LessonService_GetLessonMaterials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLessonMaterialsRequest)
	if err := dec(in); err != nil { return nil, err }
	if interceptor == nil { return srv.(LessonServiceServer).GetLessonMaterials(ctx, in) }
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/lesson.LessonService/GetLessonMaterials"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) { return srv.(LessonServiceServer).GetLessonMaterials(ctx, req.(*GetLessonMaterialsRequest)) }
	return interceptor(ctx, in, info, handler)
}

func (UnimplementedLessonServiceServer) GetAttendance(context.Context, *GetAttendanceRequest) (*AttendanceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendance not implemented")
}

func _LessonService_GetAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceRequest)
	if err := dec(in); err != nil { return nil, err }
	if interceptor == nil { return srv.(LessonServiceServer).GetAttendance(ctx, in) }
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/lesson.LessonService/GetAttendance"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) { return srv.(LessonServiceServer).GetAttendance(ctx, req.(*GetAttendanceRequest)) }
	return interceptor(ctx, in, info, handler)
}

func (c *lessonServiceClient) GetAttendance(ctx context.Context, in *GetAttendanceRequest, opts ...grpc.CallOption) (*AttendanceList, error) {
	out := new(AttendanceList)
	err := c.cc.Invoke(ctx, "/lesson.LessonService/GetAttendance", in, out, opts...)
	if err != nil { return nil, err }
	return out, nil
}
