// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: lesson.proto

package lessonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LessonStatus int32

const (
	LessonStatus_LESSON_STATUS_UNSPECIFIED          LessonStatus = 0
	LessonStatus_LESSON_STATUS_PLANNED              LessonStatus = 1
	LessonStatus_LESSON_STATUS_COMPLETED            LessonStatus = 2
	LessonStatus_LESSON_STATUS_CANCELLED            LessonStatus = 3
	LessonStatus_LESSON_STATUS_PENDING_CONFIRMATION LessonStatus = 4
	LessonStatus_LESSON_STATUS_AWAITING_PAYMENT     LessonStatus = 5
	LessonStatus_LESSON_STATUS_PAYMENT_EXPIRED      LessonStatus = 6
)

// Enum value maps for LessonStatus.
var (
	LessonStatus_name = map[int32]string{
		0: "LESSON_STATUS_UNSPECIFIED",
		1: "LESSON_STATUS_PLANNED",
		2: "LESSON_STATUS_COMPLETED",
		3: "LESSON_STATUS_CANCELLED",
		4: "LESSON_STATUS_PENDING_CONFIRMATION",
		5: "LESSON_STATUS_AWAITING_PAYMENT",
		6: "LESSON_STATUS_PAYMENT_EXPIRED",
	}
	LessonStatus_value = map[string]int32{
		"LESSON_STATUS_UNSPECIFIED":          0,
		"LESSON_STATUS_PLANNED":              1,
		"LESSON_STATUS_COMPLETED":            2,
		"LESSON_STATUS_CANCELLED":            3,
		"LESSON_STATUS_PENDING_CONFIRMATION": 4,
		"LESSON_STATUS_AWAITING_PAYMENT":     5,
		"LESSON_STATUS_PAYMENT_EXPIRED":      6,
	}
)

func (x LessonStatus) Enum() *LessonStatus {
	p := new(LessonStatus)
	*p = x
	return p
}

func (x LessonStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LessonStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_lesson_proto_enumTypes[0].Descriptor()
}

func (LessonStatus) Type() protoreflect.EnumType {
	return &file_lesson_proto_enumTypes[0]
}

func (x LessonStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LessonStatus.Descriptor instead.
func (LessonStatus) EnumDescriptor() ([]byte, []int) {
	return file_lesson_proto_rawDescGZIP(), []int{0}
}

type Lesson struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId        string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	TutorId         string                 `protobuf:"bytes,3,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	Title           string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	ScheduledAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	VideoLink       string                 `protobuf:"bytes,7,opt,name=video_link,json=videoLink,proto3" json:"video_link,omitempty"`
	Status          LessonStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=lesson.LessonStatus" json:"status,omitempty"`
	StudentId       string                 `protobuf:"bytes,9,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Price           float64                `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	PaymentDeadline *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=payment_deadline,json=paymentDeadline,proto3" json:"payment_deadline,omitempty"`
	Description     string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	StudentRating   int32                  `protobuf:"varint,13,opt,name=student_rating,json=studentRating,proto3" json:"student_rating,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_lesson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_lesson_proto_rawDescGZIP(), []int{0}
}

func (x *Lesson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lesson) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Lesson) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Lesson) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *Lesson) GetVideoLink() string {
	if x != nil {
		return x.VideoLink
	}
	return ""
}

func (x *Lesson) GetStatus() LessonStatus {
	if x != nil {
		return x.Status
	}
	return LessonStatus_LESSON_STATUS_UNSPECIFIED
}

func (x *Lesson) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Lesson) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Lesson) GetPaymentDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.PaymentDeadline
	}
	return nil
}

func (x *Lesson) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lesson) GetStudentRating() int32 {
	if x != nil {
		return x.StudentRating
	}
	return 0
}

type CreateLessonRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourseId        string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ScheduledAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	VideoLink       string                 `protobuf:"bytes,5,opt,name=video_link,json=videoLink,proto3" json:"video_link,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateLessonRequest) Reset() {
	*x = CreateLessonRequest{}
	mi := &file_lesson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonRequest) ProtoMessage() {}

func (x *CreateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateLessonRequest) Descriptor() ([]byte, []int) {
	return file_lesson_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLessonRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLessonRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *CreateLessonRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *CreateLessonRequest) GetVideoLink() string {
	if x != nil {
		return x.VideoLink
	}
	return ""
}

func (x *CreateLessonRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonRequest) Reset() {
	*x = GetLessonRequest{}
	mi := &file_lesson_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonRequest) ProtoMessage() {}

func (x *GetLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonRequest.ProtoReflect.Descriptor instead.
func (*GetLessonRequest) Descriptor() ([]byte, []int) {
	return file_lesson_proto_rawDescGZIP(), []int{2}
}

func (x *GetLessonRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type GetCourseLessonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseLessonsRequest) Reset() {
	*x = GetCourseLessonsRequest{}
	mi := &file_lesson_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseLessonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseLessonsRequest) ProtoMessage() {}

func (x *GetCourseLessonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseLessonsRequest.ProtoReflect.Descriptor instead.
func (*GetCourseLessonsRequest) Descriptor() ([]byte, []int) {
	return file_lesson_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseLessonsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type CourseLessonsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lessons       []*Lesson              `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseLessonsList) Reset() {
	*x = CourseLessonsList{}
	mi := &file_lesson_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseLessonsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseLessonsList) ProtoMessage() {}

func (x *CourseLessonsList) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseLessonsList.ProtoReflect.Descriptor instead.
func (*CourseLessonsList) Descriptor() ([]byte, []int) {
	return file_lesson_proto_rawDescGZIP(), []int{4}
}

func (x *CourseLessonsList) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type UpdateLessonStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Status        LessonStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=lesson.LessonStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonStatusRequest) Reset() {
	*x = UpdateLessonStatusRequest{}
	mi := &file_lesson_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonStatusRequest) ProtoMessage() {}

func (x *UpdateLessonStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateLessonStatusRequest) Descriptor() ([]byte, []int) {
	return file_lesson_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLessonStatusRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *UpdateLessonStatusRequest) GetStatus() LessonStatus {
	if x != nil {
		return x.Status
	}
	return LessonStatus_LESSON_STATUS_UNSPECIFIED
}

type DeleteLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonRequest) Reset() {
	*x = DeleteLessonRequest{}
	mi := &file_lesson_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonRequest) ProtoMessage() {}

func (x *DeleteLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonRequest.ProtoReflect.Descriptor instead.
func (*DeleteLessonRequest) Descriptor() ([]byte, []int) {
	return file_lesson_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLessonRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_lesson_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_lesson_proto_rawDescGZIP(), []int{7}
}

var File_lesson_proto protoreflect.FileDescriptor

const file_lesson_proto_rawDesc = "" +
	"\n" +
	"\flesson.proto\x12\x06lesson\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x03\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x19\n" +
	"\btutor_id\x18\x03 \x01(\tR\atutorId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12=\n" +
	"\fscheduled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x05R\x0fdurationMinutes\x12\x1d\n" +
	"\n" +
	"video_link\x18\a \x01(\tR\tvideoLink\x12,\n" +
	"\x06status\x18\b \x01(\x0e2\x14.lesson.LessonStatusR\x06status\x12\x1d\n" +
	"\n" +
	"student_id\x18\t \x01(\tR\tstudentId\x12\x14\n" +
	"\x05price\x18\n" +
	" \x01(\x01R\x05price\x12E\n" +
	"\x10payment_deadline\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0fpaymentDeadline\x12 \n" +
	"\vdescription\x18\f \x01(\tR\vdescription\x12%\n" +
	"\x0estudent_rating\x18\r \x01(\x05R\rstudentRating\"\xf3\x01\n" +
	"\x13CreateLessonRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12=\n" +
	"\fscheduled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\x12\x1d\n" +
	"\n" +
	"video_link\x18\x05 \x01(\tR\tvideoLink\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"/\n" +
	"\x10GetLessonRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\"6\n" +
	"\x17GetCourseLessonsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"=\n" +
	"\x11CourseLessonsList\x12(\n" +
	"\alessons\x18\x01 \x03(\v2\x0e.lesson.LessonR\alessons\"f\n" +
	"\x19UpdateLessonStatusRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.lesson.LessonStatusR\x06status\"2\n" +
	"\x13DeleteLessonRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\"\a\n" +
	"\x05Empty*\xf1\x01\n" +
	"\fLessonStatus\x12\x1d\n" +
	"\x19LESSON_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LESSON_STATUS_PLANNED\x10\x01\x12\x1b\n" +
	"\x17LESSON_STATUS_COMPLETED\x10\x02\x12\x1b\n" +
	"\x17LESSON_STATUS_CANCELLED\x10\x03\x12&\n" +
	"\"LESSON_STATUS_PENDING_CONFIRMATION\x10\x04\x12\"\n" +
	"\x1eLESSON_STATUS_AWAITING_PAYMENT\x10\x05\x12!\n" +
	"\x1dLESSON_STATUS_PAYMENT_EXPIRED\x10\x062\xd8\x02\n" +
	"\rLessonService\x12;\n" +
	"\fCreateLesson\x12\x1b.lesson.CreateLessonRequest\x1a\x0e.lesson.Lesson\x125\n" +
	"\tGetLesson\x12\x18.lesson.GetLessonRequest\x1a\x0e.lesson.Lesson\x12N\n" +
	"\x10GetCourseLessons\x12\x1f.lesson.GetCourseLessonsRequest\x1a\x19.lesson.CourseLessonsList\x12G\n" +
	"\x12UpdateLessonStatus\x12!.lesson.UpdateLessonStatusRequest\x1a\x0e.lesson.Lesson\x12:\n" +
	"\fDeleteLesson\x12\x1b.lesson.DeleteLessonRequest\x1a\r.lesson.EmptyB\x1fZ\x1dlesson-service/proto/lessonpbb\x06proto3"

var (
	file_lesson_proto_rawDescOnce sync.Once
	file_lesson_proto_rawDescData []byte
)

func file_lesson_proto_rawDescGZIP() []byte {
	file_lesson_proto_rawDescOnce.Do(func() {
		file_lesson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lesson_proto_rawDesc), len(file_lesson_proto_rawDesc)))
	})
	return file_lesson_proto_rawDescData
}

var file_lesson_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lesson_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lesson_proto_goTypes = []any{
	(LessonStatus)(0),                 // 0: lesson.LessonStatus
	(*Lesson)(nil),                    // 1: lesson.Lesson
	(*CreateLessonRequest)(nil),       // 2: lesson.CreateLessonRequest
	(*GetLessonRequest)(nil),          // 3: lesson.GetLessonRequest
	(*GetCourseLessonsRequest)(nil),   // 4: lesson.GetCourseLessonsRequest
	(*CourseLessonsList)(nil),         // 5: lesson.CourseLessonsList
	(*UpdateLessonStatusRequest)(nil), // 6: lesson.UpdateLessonStatusRequest
	(*DeleteLessonRequest)(nil),       // 7: lesson.DeleteLessonRequest
	(*Empty)(nil),                     // 8: lesson.Empty
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_lesson_proto_depIdxs = []int32{
	9,  // 0: lesson.Lesson.scheduled_at:type_name -> google.protobuf.Timestamp
	0,  // 1: lesson.Lesson.status:type_name -> lesson.LessonStatus
	9,  // 2: lesson.Lesson.payment_deadline:type_name -> google.protobuf.Timestamp
	9,  // 3: lesson.CreateLessonRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	1,  // 4: lesson.CourseLessonsList.lessons:type_name -> lesson.Lesson
	0,  // 5: lesson.UpdateLessonStatusRequest.status:type_name -> lesson.LessonStatus
	2,  // 6: lesson.LessonService.CreateLesson:input_type -> lesson.CreateLessonRequest
	3,  // 7: lesson.LessonService.GetLesson:input_type -> lesson.GetLessonRequest
	4,  // 8: lesson.LessonService.GetCourseLessons:input_type -> lesson.GetCourseLessonsRequest
	6,  // 9: lesson.LessonService.UpdateLessonStatus:input_type -> lesson.UpdateLessonStatusRequest
	7,  // 10: lesson.LessonService.DeleteLesson:input_type -> lesson.DeleteLessonRequest
	1,  // 11: lesson.LessonService.CreateLesson:output_type -> lesson.Lesson
	1,  // 12: lesson.LessonService.GetLesson:output_type -> lesson.Lesson
	5,  // 13: lesson.LessonService.GetCourseLessons:output_type -> lesson.CourseLessonsList
	1,  // 14: lesson.LessonService.UpdateLessonStatus:output_type -> lesson.Lesson
	8,  // 15: lesson.LessonService.DeleteLesson:output_type -> lesson.Empty
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_lesson_proto_init() }
func file_lesson_proto_init() {
	if File_lesson_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lesson_proto_rawDesc), len(file_lesson_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lesson_proto_goTypes,
		DependencyIndexes: file_lesson_proto_depIdxs,
		EnumInfos:         file_lesson_proto_enumTypes,
		MessageInfos:      file_lesson_proto_msgTypes,
	}.Build()
	File_lesson_proto = out.File
	file_lesson_proto_goTypes = nil
	file_lesson_proto_depIdxs = nil
}
